 <form @submit.prevent="addMember(newMember)">
    <input type="text"
      name="name"
      placeholder="name"
      v-model="newMember.name" />
    <input type="text"
      name="area"
      placeholder="area"
      v-model="newMember.area" />
    <input type="text"
      name="jobtitle"
      placeholder="jobtitle"
      v-model="newMember.jobtitle" />
    <input type="text"
      name="picture"
      placeholder="picture"
      v-model="newMember.picture" />
    <input type="tel"
      name="phone"
      placeholder="phone"
      v-model="newMember.phone" />
    <input type="email"
      name="email"
      placeholder="email"
      v-model="newMember.email" />
    <textarea name="bio"
      placeholder="bio"
      v-model="newMember.bio"></textarea>
    <button type="submit">Enviar</button>
  </form>